backstage/techdocs-cli

packages/techdocs-cli/package.json
packages/techdocs-cli/src/commands/serve/serve.ts

The path of the Backstage app bundle would not work when @techdocs/cli package will be bundled for release. Previously, by pure co-incidence the path was the same when developing locally as well as after bundling for release.

Fix serve command due to misconfigured bundle path

---

packages/techdocs-cli/package.json
packages/techdocs-cli/src/commands/index.ts
packages/techdocs-cli/src/commands/publish/publish.ts
yarn.lock

I'm in the process of setting up publishing via CI/CD to Azure Blob Storage. I found that `@techdocs/cli` is not aware of `azureBlobStorage`. It gives `error: Unknown publisher type azureBlobStorag` when trying to publish using `npx @techdocs/cli publish --publisher-type azureBlobStorage`.
1. Added `azureBlobStorage` as an option. 
2. According to [Configuring Azure Blob Storage Container with TechDocs](https://backstage.io/docs/features/techdocs/using-cloud-storage#configuring-azure-blob-storage-container-with-techdocs), Azure Blob Storage configuration needs `containerName` instead of `bucketName` so I'm using that key. 
3. Added an `--azureAccountName` argument to publish command which allows activating authentication with Azure.
4. Added `--azureAccountKey` argument to provide …

Make azureBlobStorage one of the publish options

---

packages/embedded-techdocs/package.json
packages/embedded-techdocs/yarn.lock
packages/techdocs-cli/package.json
yarn.lock

- Bumps backstage versions using the cli tool
- Bumps techdocs-common to ensure the [awsS3 upload patch](https://github.com/backstage/backstage/commit/61299519fb853a65ab7af66506cb2ee86e564098) is included
- Release patch version (not sure if this should be minor? the cli bump is quite large?)
I was making this bump mostly for the upload of images to S3 so that's what I've manually checked (with patch followed by without patch, definitely works 💯)

Release new version with bump to backstage packages

---

README.md
packages/techdocs-cli/package.json
packages/techdocs-cli/src/commands/index.ts
packages/techdocs-cli/src/commands/publish/publish.ts
yarn.lock

fix #36 
fix #37
I'm waiting on the next release of backstage to update the `@backstage/techdocs-common` dependency

Add awsRoleArn and awsEndpoint option to publish command

---

README.md

Tweaks some minor wording, including removing a duplication in the publish section.
Tries to keep consistent across generate and publish, with a quick code fence at top for the command, some description, and then the full command reference.
Signed-off-by: Adam Harvey <adam.harvey@dxc.com>

Update wording on README

---

packages/embedded-techdocs/packages/app/package.json
packages/embedded-techdocs/yarn.lock
packages/techdocs-cli/package.json
yarn.lock

Bumping to `@backstage/plugin-techdocs^0.9.0` fixes the WSOD when running `techdics-cli serve`.  The change in `0.9.0` to use `<EntityRefLink />` in the header component resolves an issue where Backstage didn't know how to resolve the entity page links in the header.
Closes #46

Fix techdocs-cli serve WSOD

---

docs/README.md

Signed-off-by: Adam Harvey <adaharve@cisco.com>
Fixes a broken image link in the README.  Using the new GitHub feature where the main README can actually come from `docs/README.md`, the referenced image is now one folder too deep. Just linked it back up to root to get to the `/.github` root folder, and it now looks good in my fork.
| Before | After |
| --- | --- |
| <img width="660" alt="image" src="https://user-images.githubusercontent.com/33203301/118316695-23604200-b4c5-11eb-9585-7f07746d256f.png"> | <img width="660" alt="image" src="https://user-images.githubusercontent.com/33203301/118316745-31ae5e00-b4c5-11eb-9822-38e04ad89f8f.png"> |

Fix broken image link in README

---

packages/techdocs-cli/package.json
packages/techdocs-cli/src/lib/mkdocsServer.test.ts
packages/techdocs-cli/src/lib/mkdocsServer.ts

Signed-off-by: Emma Indal <emmai@spotify.com>
closes: #45 
I did plan to write a test for this, something like
```
it("can serve:mkdocs from dir with spaces", async () => {
jest.setTimeout(10000);
const proc = await executeTechDocsCliCommand(["serve:mkdocs"], {
cwd: "./src/mocks/mock docs",
killAfter: 8000
});
expect(proc.combinedStdOutErr).toContain("Starting mkdocs server on");
});
```
but since this only happens when using docker and not when using the --no-docker flag, we need to depend on docker in CI I believe, since the e2e test is ran there. Let me know if you think we should do that or skip the test!

Fix bug when running serve:mkdocs from directory including spaces

---

packages/techdocs-cli/src/commands/index.ts
packages/techdocs-cli/src/commands/publish/publish.ts

**Add openStackSwift publisher type**
`publisher-type` option was setted to accept `awsS3` / `GoogleGcs` / `azureBlobStorage` - same as the variable `techdocs.publisher.type` in backstage config file.
But in backstage config file, there is another option: `openStackSwift` and `techdocs-cli` wasn't ready to accept this option even if `techdocs-common` had everything to handle it.
This PR added 7 more options (4 mandatory / 3 optionals) to match the options of openStackSwift storage connector described [here](https://github.com/backstage/backstage/blob/master/packages/techdocs-common/src/stages/publish/openStackSwift.ts#L65)
1. `osUsername` | **Mandatory** (if `openStackSwift`)
2. `osPassword` | **Mandatory** (if `openStackSwift`)
3. `osAuthUrl` | **Mandatory** (if `openStackSwift`)
4. …

feat: add new options in order to use openstackswift publisher

---

docs/README.md
packages/techdocs-cli/src/commands/index.ts
packages/techdocs-cli/src/commands/serve/mkdocs.ts
packages/techdocs-cli/src/commands/serve/serve.ts
packages/techdocs-cli/src/lib/mkdocsServer.test.ts
packages/techdocs-cli/src/lib/mkdocsServer.ts

This adds new `--docker-image` command line switches to support a custom docker image. This can be useful if you want to support custom MkDocs plugins or external tools.

feat: support custom docker images

---

docs/README.md
packages/techdocs-cli/src/commands/index.ts

The default value `--docker-image` is automatically appended to the end of the CLI shell output. Since it was included in the text explicitly this shows twice.

fix: double docker-image cli description

---

docs/README.md
packages/techdocs-cli/src/commands/index.ts
packages/techdocs-cli/src/commands/publish/publish.ts

Signed-off-by: Camila Belo <camilaibs@gmail.com>
Closes: #80
Allow providers like LocalStack, Minio, Wasabi, and others to use path style when running the _publish_ command with the `--awsS3ForcePathStyle` option:
```bash
techdocs-cli publish --publisher-type=awsS3 --awsS3ForcePathStyle
```

[Publish] add option awsS3ForcePathStyle

---

packages/techdocs-cli/src/commands/generate/generate.ts

Fixes #86
The latest backstage release introduced an new required option in the generate step run method https://github.com/backstage/backstage/pull/6341/files#diff-ddd013876d02c04e8ddaad2ac791a0310e9694046c3f8db9235afd648cd86054R64. This is a quick fix. Longer term fix could be to update the `techdocs-common` generator to use the class logger when a logger is not passed directly to the run method.

fix: required logger in generate

---

packages/embedded-techdocs/packages/app/src/apis.ts

fixes #78
This removes the invalid warning banner that is displayed in the techdocs preview when running `techdocs-cli serve`

fix: invalid techdocs preview warning

---

docs/README.md
packages/techdocs-cli/src/commands/index.ts
packages/techdocs-cli/src/lib/PublisherConfig.ts

Refs:
https://github.com/backstage/backstage/issues/4367
https://github.com/backstage/backstage/pull/6709
Adds a new flag called `--legacyUseCaseSensitiveTripletPaths` to enable publishes using the legacy case sensitive triplet paths.
Signed-off-by: Camila Belo <camilaibs@gmail.com>
Co-authored-by: Eric Peterson <ericpeterson@spotify.com>

Create legacyUseCaseSensitiveTripletPaths option for publish

---

.github/workflows/main.yml

This is related to the Main Workflow.
We are getting the "_**Error TS2304: Cannot find module**_" when running `yarn tsc`:
https://github.com/backstage/techdocs-cli/runs/3288405993
Added an install step to run before the Typescript compiler.
Signed-off-by: Camila Belo <camilaibs@gmail.com>

[Chore] Install dependencies before running tsc

---

README.md
package.json
packages/embedded-techdocs-app/package.json
packages/techdocs-cli/package.json
yarn.lock

Changelog (from v0.6.0 to v0.6.1)
* [#98](https://github.com/backstage/techdocs-cli/pull/98) chore(deps): bump path-parse from 1.0.6 to 1.0.7 ([@dependabot[bot]](https://github.com/apps/dependabot))
Thank you for contributing ❤️
- Camila Belo ([@camilaibs](https://github.com/camilaibs))

Release v0.6.1

---

README.md

when changing something inside `techdocs-common` and running `techdocs-cli` locally you can set up `yarn link`
to make sure you pick up local changes instead of using a published version of techdocs-common.

readme: add information about running techdocs-common locally

---

packages/techdocs-cli/src/commands/index.ts

The azureAccountKey parameter was deleted by misstake so this PR adds it back
closing: #97

Add azureAccountKey parameter back to the publish command

---

.github/dependabot.yml

Configuring dependabot to automatically send us package version updates for all of our dependencies.
[Enable and disable updates.](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-version-updates)

Configure dependabot for all packages

---

.github/workflows/project-board.yml

Our project board workflow fails when PRs are opened up automatically by dependabot. This adds an exception and ignore the project board workflow on automatically opened dependabot PRs opened from a branch starting with `dependabot`.
[Ref documentation](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-ignoring-branches-and-tags)

ignore dependabot branches for project board workflow

---

.changeset/great-baboons-battle.md

* `techdocs-cli`
* [#105](https://github.com/backstage/techdocs-cli/pull/105) Add azureAccountKey parameter back to the publish command ([@emmaindal](https://github.com/emmaindal))
* `embedded-techdocs-app`
* [#122](https://github.com/backstage/techdocs-cli/pull/122) chore(deps-dev): bump @types/node from 12.20.20 to 16.7.1 in /packages/embedded-techdocs-app ([@dependabot[bot]](https://github.com/apps/dependabot))
* [#120](https://github.com/backstage/techdocs-cli/pull/120) chore(deps-dev): bump @types/react-dom from 16.9.14 to 17.0.9 in /packages/embedded-techdocs-app ([@dependabot[bot]](https://github.com/apps/dependabot))
* [#119](https://github.com/backstage/techdocs-cli/pull/119) chore(deps-dev): bump @testing-library/user-event from 12.8.3 to 13.2.1 in …

Release v0.6.2

---

.changeset/beta-beta-beta.md
packages/embedded-techdocs-app/package.json
packages/embedded-techdocs-app/src/App.tsx
packages/techdocs-cli/package.json
yarn.lock

This pulls in `^0.9.0` of `@backstage/techdocs-common`, which should start publishing docs to storage using the expected case by default.

Bump @backstage/techdocs-common for beta

---

.changeset/ninety-jars-press.md
.github/workflows/main.yml
package.json

Fixes: https://github.com/backstage/techdocs-cli/issues/151
In the last release, the build script ran after the publish, causing a publish not containing dist files.
This pull request aims to separate the build and publish in individual and sequential steps to guarantee the script order.

[Chore]: Separate build and publish release steps
